import os
import smtplib
from email.message import EmailMessage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import markdown
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib.colors import HexColor
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# SMTP Configuration
SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USERNAME = os.getenv("SMTP_USERNAME")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")

def generate_report_content(user_query: str, answer_markdown: str, context: list[str]) -> tuple[str, str]:
    """Generates plain text and HTML content from the RAG output."""
    
    # 1. Plain Text Report
    context_text = '\n- '.join(context) if context else 'No sources retrieved'
    
    text_content = f"""
Oracle AWR Analysis Report
{'='*60}

Query:
{user_query}

{'='*60}

Analysis Results:
{answer_markdown}

{'='*60}

Retrieved Context Sources:
- {context_text}

{'='*60}
Generated by Oracle AWR RAG Application
    """

    # 2. HTML Report
    context_html_list = ''.join([f'<li>{c}</li>' for c in context]) if context else '<li>No sources retrieved</li>'
    
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; background-color: #f5f5f5; }}
            .container {{ max-width: 900px; margin: 30px auto; padding: 30px; background: white; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
            h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
            h2 {{ color: #2980b9; border-bottom: 2px solid #ecf0f1; padding-bottom: 8px; margin-top: 25px; }}
            .query {{ background-color: #ecf0f1; padding: 15px; border-left: 5px solid #3498db; margin: 15px 0; }}
            .answer {{ background-color: #f9f9f9; padding: 20px; border-left: 5px solid #27ae60; margin: 15px 0; line-height: 1.8; }}
            .context {{ font-size: 0.9em; color: #555; margin-top: 25px; background-color: #fef9e7; padding: 15px; border-radius: 5px; }}
            .context ul {{ list-style-type: disc; padding-left: 25px; }}
            .footer {{ text-align: center; margin-top: 40px; padding-top: 20px; font-size: 0.85em; color: #999; border-top: 1px solid #ecf0f1; }}
            code {{ background-color: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-family: 'Courier New', monospace; }}
            .metric {{ background-color: #e8f4f8; padding: 8px; margin: 5px 0; border-radius: 4px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>📊 Oracle AWR Analysis Report</h1>
            
            <h2>Query</h2>
            <div class="query">
                <strong>{user_query}</strong>
            </div>
            
            <h2>Analysis Results</h2>
            <div class="answer">
                {markdown.markdown(answer_markdown)}
            </div>
            
            <h2>Retrieved Context Sources</h2>
            <div class="context">
                <ul>
                    {context_html_list}
                </ul>
            </div>
            
            <div class="footer">
                <p>Generated by <strong>Oracle AWR RAG Application</strong></p>
                <p>Powered by Advanced AI & Vector Search</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    return text_content, html_content


def generate_pdf_report(user_query: str, answer_markdown: str, context: list[str], output_path: str) -> str:
    """Generates a PDF report from RAG output with better formatting."""
    try:
        doc = SimpleDocTemplate(
            output_path, 
            pagesize=letter,
            rightMargin=50, 
            leftMargin=50,
            topMargin=50, 
            bottomMargin=30
        )
        
        elements = []
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=20,
            textColor=HexColor('#2c3e50'),
            spaceAfter=20,
            alignment=1  # Center
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=HexColor('#2980b9'),
            spaceAfter=10,
            spaceBefore=15,
        )
        
        subheading_style = ParagraphStyle(
            'SubHeading',
            parent=styles['Heading3'],
            fontSize=12,
            textColor=HexColor('#34495e'),
            spaceAfter=8,
            spaceBefore=10,
        )
        
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['BodyText'],
            fontSize=10,
            leading=14,
            spaceAfter=10,
        )
        
        bullet_style = ParagraphStyle(
            'BulletStyle',
            parent=styles['BodyText'],
            fontSize=10,
            leftIndent=20,
            bulletIndent=10,
            spaceAfter=6,
        )
        
        critical_style = ParagraphStyle(
            'CriticalStyle',
            parent=styles['BodyText'],
            fontSize=10,
            textColor=HexColor('#e74c3c'),
            leftIndent=20,
            spaceAfter=6,
        )
        
        warning_style = ParagraphStyle(
            'WarningStyle',
            parent=styles['BodyText'],
            fontSize=10,
            textColor=HexColor('#f39c12'),
            leftIndent=20,
            spaceAfter=6,
        )
        
        # Title
        elements.append(Paragraph("Oracle AWR Analysis Report", title_style))
        elements.append(Spacer(1, 10))
        
        # Metadata
        from datetime import datetime
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        metadata = f"<font size=8 color='#7f8c8d'>Generated: {timestamp}</font>"
        elements.append(Paragraph(metadata, styles['Normal']))
        elements.append(Spacer(1, 20))
        
        # Query Section
        elements.append(Paragraph("Query", heading_style))
        query_safe = user_query.replace('<', '&lt;').replace('>', '&gt;')
        elements.append(Paragraph(query_safe, body_style))
        elements.append(Spacer(1, 15))
        
        # Answer Section
        elements.append(Paragraph("Analysis Results", heading_style))
        elements.append(Spacer(1, 10))
        
        # Parse and format the answer
        answer_lines = answer_markdown.split('\n')
        
        for line in answer_lines:
            line = line.strip()
            if not line:
                elements.append(Spacer(1, 6))
                continue
            
            # Escape HTML characters
            line = line.replace('<', '&lt;').replace('>', '&gt;')
            
            # Handle headers (###, ##, #)
            if line.startswith('### '):
                text = line.replace('### ', '')
                elements.append(Paragraph(text, subheading_style))
            elif line.startswith('## '):
                text = line.replace('## ', '')
                elements.append(Paragraph(text, heading_style))
            elif line.startswith('# '):
                text = line.replace('# ', '')
                elements.append(Paragraph(text, heading_style))
            
            # Handle bold (**text**)
            elif '**' in line:
                # Replace **text** with <b>text</b>
                import re
                line = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
                elements.append(Paragraph(line, body_style))
            
            # Handle bullet points (-, *, •)
            elif line.startswith(('- ', '* ', '• ', '→ ')):
                text = line.lstrip('-*•→ ')
                elements.append(Paragraph(f"• {text}", bullet_style))
            
            # Handle numbered lists
            elif line and line[0].isdigit() and '. ' in line[:4]:
                elements.append(Paragraph(line, bullet_style))
            
            # Handle emoji indicators with appropriate styling
            elif 'CRITICAL' in line.upper() or '🔴' in line:
                line = line.replace('🔴', '[CRITICAL]')
                elements.append(Paragraph(f"<b>{line}</b>", critical_style))
            elif 'WARNING' in line.upper() or '🟡' in line:
                line = line.replace('🟡', '[WARNING]')
                elements.append(Paragraph(f"<b>{line}</b>", warning_style))
            elif 'INFO' in line or 'ℹ️' in line:
                line = line.replace('ℹ️', '[INFO]')
                elements.append(Paragraph(f"<b>{line}</b>", body_style))
            
            # Regular text
            else:
                elements.append(Paragraph(line, body_style))
        
        elements.append(Spacer(1, 20))
        
        # Retrieved Contexts Section
        elements.append(Paragraph("Retrieved Context Sources", heading_style))
        elements.append(Spacer(1, 10))
        
        if context:
            for i, ctx in enumerate(context[:5], 1):  # Limit to first 5
                ctx_safe = ctx[:400].replace('<', '&lt;').replace('>', '&gt;')
                elements.append(Paragraph(f"<b>Source {i}:</b>", subheading_style))
                elements.append(Paragraph(f"{ctx_safe}...", body_style))
                elements.append(Spacer(1, 8))
        else:
            elements.append(Paragraph("No context sources retrieved", body_style))
        
        # Footer
        elements.append(Spacer(1, 20))
        footer_text = "<font size=8 color='#95a5a6'>Oracle AWR RAG Application | Powered by AI</font>"
        elements.append(Paragraph(footer_text, styles['Normal']))
        
        # Build PDF
        doc.build(elements)
        return output_path
    
    except Exception as e:
        print(f"Error generating PDF: {e}")
        import traceback
        traceback.print_exc()
        raise


def send_email_report(to_email: str, subject: str, body: str, subtype: str = 'plain', 
                     attachment_path: str = None, attachment_content: str = None, 
                     attachment_filename: str = None):
    """
    Sends the email using the configured SMTP server.
    
    Args:
        to_email: Recipient email address
        subject: Email subject
        body: Email body content
        subtype: 'plain' or 'html'
        attachment_path: Path to file attachment (for PDF)
        attachment_content: String content to attach (for HTML/Text)
        attachment_filename: Name for the attachment file
    """
    
    if not all([SMTP_SERVER, SMTP_USERNAME, SMTP_PASSWORD]):
        print("SMTP config missing. Cannot send email.")
        print("Please set SMTP_USERNAME and SMTP_PASSWORD in .env file")
        return False
        
    try:
        msg = EmailMessage()
        msg['Subject'] = subject
        msg['From'] = SMTP_USERNAME
        msg['To'] = to_email
        
        # Set main email body
        if subtype == 'html' and not attachment_content:
            # If HTML without attachment, send HTML inline
            msg.set_content(body, subtype='html')
        elif attachment_content:
            # If there's an attachment, send simple text body
            msg.set_content(f"Please see the attached {attachment_filename.split('.')[-1].upper()} report.\n\nThis is an automated email from Oracle AWR RAG Application.")
        else:
            # Plain text
            msg.set_content(body, subtype=subtype)
        
        # Handle file attachment (PDF)
        if attachment_path and os.path.exists(attachment_path):
            with open(attachment_path, 'rb') as fp:
                file_data = fp.read()
                msg.add_attachment(
                    file_data, 
                    maintype='application', 
                    subtype='pdf', 
                    filename=os.path.basename(attachment_path)
                )
        
        # Handle string content attachment (HTML or Text)
        if attachment_content and attachment_filename:
            if attachment_filename.endswith('.html'):
                msg.add_attachment(
                    attachment_content.encode('utf-8'),
                    maintype='text',
                    subtype='html',
                    filename=attachment_filename
                )
            else:  # .txt
                msg.add_attachment(
                    attachment_content.encode('utf-8'),
                    maintype='text',
                    subtype='plain',
                    filename=attachment_filename
                )

        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.send_message(msg)
        
        return True
    
    except Exception as e:
        print(f"Error sending email: {e}")
        import traceback
        traceback.print_exc()
        return False