import os
import smtplib
from email.message import EmailMessage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import markdown

# ReportLab imports for PDF generation
try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.enums import TA_JUSTIFY
    from reportlab.lib.colors import HexColor
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    print("Warning: reportlab not installed. PDF generation will not work.")

# Load environment variables
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    print("Warning: python-dotenv not installed. Using default SMTP config.")

# SMTP Configuration
SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USERNAME = os.getenv("SMTP_USERNAME")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")

def generate_report_content(user_query: str, answer_markdown: str, context: list[str]) -> tuple[str, str]:
    """Generates plain text and HTML content from the RAG output."""
    
    # 1. Plain Text Report
    context_text = '\n- '.join(context) if context else 'No sources retrieved'
    
    text_content = f"""
RAG System Report
---
Query: {user_query}
---
Answer:
{answer_markdown}
---
Retrieved Sources:
- {context_text}
    """

    # 2. HTML Report (from Markdown)
    context_html_list = ''.join([f'<li>{c}</li>' for c in context]) if context else '<li>No sources retrieved</li>'
    
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; }}
            .container {{ max-width: 800px; margin: auto; padding: 20px; border: 1px solid #ccc; }}
            h2 {{ color: #333; border-bottom: 2px solid #eee; padding-bottom: 5px; }}
            .answer {{ background-color: #f9f9f9; padding: 15px; border-left: 5px solid #007bff; }}
            .context {{ font-size: 0.9em; color: #555; margin-top: 20px; }}
            .context ul {{ list-style-type: disc; padding-left: 20px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>RAG Query Report</h1>
            <h2>Query</h2>
            <p><strong>{user_query}</strong></p>
            
            <h2>Answer</h2>
            <div class="answer">
                {markdown.markdown(answer_markdown)}
            </div>
            
            <h2>Retrieved Contexts</h2>
            <div class="context">
                <ul>
                    {context_html_list}
                </ul>
            </div>
            <p style="text-align: center; margin-top: 30px; font-size: 0.8em; color: #999;">
                Generated by your RAG System.
            </p>
        </div>
    </body>
    </html>
    """
    
    return text_content, html_content


def generate_pdf_report(user_query: str, answer_markdown: str, context: list[str], output_path: str) -> str:
    """Generates a PDF report from RAG output."""
    
    if not REPORTLAB_AVAILABLE:
        raise ImportError("reportlab is not installed. Please install it with: pip install reportlab")
    
    try:
        doc = SimpleDocTemplate(
            output_path, 
            pagesize=letter,
            rightMargin=72, 
            leftMargin=72,
            topMargin=72, 
            bottomMargin=18
        )
        
        # Container for the 'Flowable' objects
        elements = []
        
        # Define styles
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            spaceAfter=12,
            spaceBefore=12,
        )
        
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['BodyText'],
            fontSize=11,
            alignment=TA_JUSTIFY,
            spaceAfter=12,
        )
        
        # Add content
        elements.append(Paragraph("RAG Query Report", title_style))
        elements.append(Spacer(1, 12))
        
        # Query section
        elements.append(Paragraph("Query", heading_style))
        query_safe = user_query.replace('<', '&lt;').replace('>', '&gt;')
        elements.append(Paragraph(query_safe, body_style))
        elements.append(Spacer(1, 12))
        
        # Answer section
        elements.append(Paragraph("Answer", heading_style))
        # Convert markdown to plain text for PDF (basic conversion)
        answer_text = answer_markdown.replace('**', '').replace('*', '').replace('#', '')
        answer_text = answer_text.replace('<', '&lt;').replace('>', '&gt;')
        elements.append(Paragraph(answer_text, body_style))
        elements.append(Spacer(1, 12))
        
        # Contexts section
        elements.append(Paragraph("Retrieved Contexts", heading_style))
        if context:
            for i, ctx in enumerate(context[:5], 1):  # Limit to first 5 contexts
                ctx_safe = ctx[:500].replace('<', '&lt;').replace('>', '&gt;')
                ctx_text = f"{i}. {ctx_safe}..."
                elements.append(Paragraph(ctx_text, body_style))
                elements.append(Spacer(1, 6))
        else:
            elements.append(Paragraph("No contexts retrieved", body_style))
        
        # Build PDF
        doc.build(elements)
        return output_path
    
    except Exception as e:
        print(f"Error generating PDF: {e}")
        raise


def send_email_report(to_email: str, subject: str, body: str, subtype: str = 'plain', attachment_path: str = None):
    """Sends the email using the configured SMTP server."""
    
    if not all([SMTP_SERVER, SMTP_USERNAME, SMTP_PASSWORD]):
        print("SMTP config missing. Cannot send email.")
        print("Please set SMTP_USERNAME and SMTP_PASSWORD in .env file")
        return False
        
    try:
        msg = EmailMessage()
        msg['Subject'] = subject
        msg['From'] = SMTP_USERNAME
        msg['To'] = to_email
        
        # Set content based on subtype ('plain' or 'html')
        msg.set_content(body, subtype=subtype)

        # Handle file attachment if provided
        if attachment_path and os.path.exists(attachment_path):
            with open(attachment_path, 'rb') as fp:
                file_data = fp.read()
                msg.add_attachment(
                    file_data, 
                    maintype='application', 
                    subtype='pdf' if attachment_path.endswith('.pdf') else 'octet-stream', 
                    filename=os.path.basename(attachment_path)
                )

        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()  # Upgrade connection to secure TLS
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.send_message(msg)
        
        return True
    
    except Exception as e:
        print(f"Error sending email: {e}")
        import traceback
        traceback.print_exc()
        return False